import { PropsWithChildren } from 'react';
import { styled, theme } from 'stiches.config';

import Section from '@components/Section';
import LayoutWithNavbar from '@layouts/LayoutWithNavbar';
import { CSS } from '@stitches/react';

const Container = styled('div', {
	marginTop: '2rem',
	h1: { fontSize: '2rem' },
	h2: { margin: '0 0 .5rem 0' },
	p: { marginTop: 0, color: theme.colors.textMedium },
	'& p:last-child': { margin: 0 },
	'& > *:not(:last-child)': { marginBottom: '2rem' },
});

const sectionCss: CSS = {};
const headerCss: CSS = { padding: '.5rem 1rem' };
const contentCss: CSS = { padding: '1rem' };

const CustomSection = ({ children }: PropsWithChildren) => <Section css={sectionCss}>{children}</Section>;
const CustomHeader = ({ children }: PropsWithChildren) => <Section.Header css={headerCss}>{children}</Section.Header>;
const CustomContent = ({ children }: PropsWithChildren) => (
	<Section.Content css={contentCss}>{children}</Section.Content>
);

const Agreement = () => {
	return (
		<Container>
			<CustomSection>
				<CustomHeader>Terms & Conditions and Privacy Policy</CustomHeader>
				<CustomContent>
					<h2>Cookies</h2>
					<p>
						When you are signed in, a cookie is used to track who you are; it contains a simple unique
						string used to identify your requests.
					</p>
					<p>
						If a 3rd person gets a hold of this cookie, they can gain access to your account. It is as
						secure as your browser is.
					</p>
					<h2>Local Storage</h2>
					<p>We use local storage to hold data that we deem low security.</p>
					<h2>Use of Google User Data</h2>
					<p>
						You have the option of signing up for KroyOoz.gg with your Google account. As part of the sign
						up process, KroyOoz.gg will obtain data from Google that allows it to uniquely identify you.
						This includes your Google account&apos;s primary email address, and a unique identifier for the
						account generated by Google. This data is used to link you to your KroyOoz.gg account and allows
						for future sign ins so long as you have access to your Google account.
					</p>
					<p>
						The data referenced above is stored in a database on a secure server only accessible to
						administrators. It will never be shared with a third party.
					</p>
				</CustomContent>
			</CustomSection>
			<CustomSection>
				<CustomHeader>Account Deletion</CustomHeader>
				<CustomContent>
					<p>
						You can request account removal via your profile. We will action this within 30 days of your
						submission.
						<br />
						Your private messages, even when deleted via your profile, are not removed from the recipients
						inbox (but usernames are obfuscated).
					</p>
				</CustomContent>
			</CustomSection>
			<CustomSection>
				<CustomHeader>Data Access</CustomHeader>
				<CustomContent>
					<p>
						Any user may request a full output of their data at any point. An admin will provide these
						details within a reasonable amount of time.
					</p>
				</CustomContent>
			</CustomSection>
			<CustomSection>
				<CustomHeader>User Agreement</CustomHeader>
				<CustomContent>
					<p>You must not attempt to gain access to data or user accounts that are not yours.</p>
				</CustomContent>
			</CustomSection>
		</Container>
	);
};

Agreement.getLayout = function getLayout(page: JSX.Element) {
	return <LayoutWithNavbar>{page}</LayoutWithNavbar>;
};

Agreement.title = 'Terms & Privacy';

export default Agreement;
